spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # copy configuration folder to ~/fs-config
          search-locations: "file:${user.home}//fs-config"

server:
  port: 8071
